name: Xata Clone (daily, on-demand)

on:
  schedule:
    - cron: "0 8 * * *" # Clone production to staging nightly
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
  XATA_API_ENVIRONMENT: prod
  XATA_ORGANIZATIONID: xata
  XATA_PROJECTID: prj_9kttr5nbl16rn5qu24rvtblujg
  XATA_BRANCHID: pa8dfj56th26r3ib4nml5psm94
  XATA_BRANCHNAME: clone-target
  XATA_DATABASENAME: app
  # source is main branch in the same project
  XATA_CLI_SOURCE_POSTGRES_URL: ${{ secrets.SOURCE_DATABASE_URL }}
  PGSTREAM_POSTGRES_SNAPSHOT_ROLE: postgres

jobs:
  xata-clone:
    name: Xata Clone
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          # This makes the PR pushed to use GITHUB_TOKEN and trigger the checks
          persist-credentials: false

      - name: Install PostgreSQL client 17
        run: |
          sudo install -d /usr/share/keyrings
          wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc \
            | sudo gpg --dearmor -o /usr/share/keyrings/postgresql.gpg
          echo "deb [signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" \
            | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17
          echo "/usr/lib/postgresql/17/bin" >> "$GITHUB_PATH"
          which pg_dump
          pg_dump --version

      - name: Install Xata CLI
        run: |
          curl -fsSL https://xata.io/install.sh | bash
          echo "/home/runner/.config/xata/bin" >> $GITHUB_PATH

      - name: Check Xata Version and Status
        run: |
          xata version
          xata status
          xata branch view

      - name: Xata Clone
        run: |
          xata clone start --source-url ${{ env.XATA_CLI_SOURCE_POSTGRES_URL }} --validation-mode=relaxed
