name: Delete PR branch on PR merge/close

on:
  pull_request:
    types: [closed, merged]

jobs:
  cleanup:
    name: Delete PR branch on PR merge/close
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v4

      - name: Set Xata Environment Variables
        shell: bash
        run: |
          echo "XATA_API_KEY=${{ secrets.XATA_API_KEY }}" >> $GITHUB_ENV
          echo "XATA_API_ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "XATA_ORGANIZATIONID=xata" >> $GITHUB_ENV
          echo "XATA_PROJECTID=prj_9kttr5nbl16rn5qu24rvtblujg" >> $GITHUB_ENV
          echo "XATA_BRANCHID=e80atan1sl5khdkr8pkc33fovk" >> $GITHUB_ENV
          echo "XATA_BRANCHNAME=main" >> $GITHUB_ENV
          echo "XATA_DATABASENAME=app" >> $GITHUB_ENV

      - name: Install Xata CLI
        shell: bash
        run: |
          curl -fsSL https://xata.io/install.sh | bash
          echo "/home/runner/.config/xata/bin" >> $GITHUB_PATH

      - name: Delete Preview Branch
        run: xata branch delete "${{ github.event.pull_request.head.ref }}_${{ github.event.pull_request.number }}" --yes || true
